
# clock variable
FRAMERATE = 60

# size variables
BOX_WIDTH = 20
BOX_HEIGHT = 20
NUM_BOX_ROWS = 20
NUM_BOX_COLS= 10
SCREEN_WIDTH = BOX_WIDTH * NUM_BOX_COLS
SCREEN_HEIGHT = BOX_HEIGHT * NUM_BOX_ROWS
BOX_DIVISION = 1
GRID_WIDTH = NUM_BOX_COLS * BOX_DIVISION
GRID_HEIGHT = NUM_BOX_ROWS * BOX_DIVISION

# movement variables
SIDE_STEP = BOX_DIVISION# left right movement 
DROP_TIMING = 20 # falling speed, how many fps before it falls
FALL_STEP = 1