#Controller and model items
GRID_WIDTH = 10
GRID_HEIGHT = 20



#pygame items
FPS = 60
FALL_SPEED = 2 #blocks a second
BOX_WIDTH = 20
BOX_HEIGHT = 20
SCREEN_WIDTH = GRID_WIDTH * BOX_WIDTH
SCREEN_HEIGHT = GRID_HEIGHT * BOX_HEIGHT